### ISSUE TITLE
Add Password Visibility Toggle Button

### ISSUE THREAD

**Issue by Photon3009** [Photon3009/Auberge#13]
Currently, our password fields lack a visibility toggle button, which allows users to obscure or unobscure their passwords. This feature is crucial for user convenience and security. We need to implement a button that toggles between showing and obscuring the password text in the password field.

**Comment by Anushkabh** [comment]
kindly assign me this issue under jwoc'24

**Comment by Photon3009** [comment]
@Anushkabh assigned!

**Comment by himanshiiiiii** [comment]
> Currently, our password fields lack a visibility toggle button, which allows users to obscure or unobscure their passwords. This feature is crucial for user convenience and security. We need to implement a button that toggles between showing and obscuring the password text in the password field.

@Photon3009 Plzz assign this issue to me I have already done it

Sample
![visible](https://github.com/Photon3009/Auberge/assets/99973728/4e7e55d1-3934-45ec-b9ce-ff1851453f71)
![invisible](https://github.com/Photon3009/Auberge/assets/99973728/d62bec92-9b04-4778-b763-8cf0bef399bf)

**Comment by himanshiiiiii** [comment]
> > Currently, our password fields lack a visibility toggle button, which allows users to obscure or unobscure their passwords. This feature is crucial for user convenience and security. We need to implement a button that toggles between showing and obscuring the password text in the password field.
> 
> @Photon3009 Plzz assign this issue to me I have already done it
> 
> Sample
> ![visible](https://github.com/Photon3009/Auberge/assets/99973728/4e7e55d1-3934-45ec-b9ce-ff1851453f71)
> ![invisible](https://github.com/Photon3009/Auberge/assets/99973728/d62bec92-9b04-4778-b763-8cf0bef399bf)
> 

@Photon3009 plzz assign me this issue under JWOC

**Comment by Photon3009** [comment]
@himanshiiiiii assigned you, and just a suggestion: whenever you try to add an image in a PR or in the issue section, please reduce it to a comfortable size

**Comment by himanshiiiiii** [comment]
> @himanshiiiiii assigned you, and just a suggestion: whenever you try to add an image in a PR or in the issue section, please reduce it to a comfortable size

Ok

**Comment by himanshiiiiii** [comment]
> Currently, our password fields lack a visibility toggle button, which allows users to obscure or unobscure their passwords. This feature is crucial for user convenience and security. We need to implement a button that toggles between showing and obscuring the password text in the password field.

@Photon3009 it's done
