### ISSUE TITLE
Code Refactoring: Improving Code Quality and Readability

### ISSUE THREAD

**Issue by Photon3009** [Photon3009/Auberge#2]

**Comment by himanshiiiiii** [comment]
Plzz assign this issue to me

**Comment by Photon3009** [comment]
@himanshiiiiii I have assigned this issue to you. You can make a PR after the coding period starts(15th Jan) for JWOC. Until then, feel free to work on it and ask if any doubts arise

**Comment by himanshiiiiii** [comment]
> @himanshiiiiii I have assigned this issue to you. You can make a PR after the coding period starts(15th Jan) for JWOC. Until then, feel free to work on it and ask if any doubts arise

Ok thnk u

**Comment by Photon3009** [comment]
@himanshiiiiii any progress?

**Comment by himanshiiiiii** [comment]
> @himanshiiiiii any progress?

Still working
