### ISSUE TITLE
Add Dark Mode

### ISSUE THREAD

**Issue by Photon3009** [Photon3009/Auberge#3]
Introduce a dark mode option to provide users with an alternative color scheme that is easier on the eyes and conserves battery life on OLED screens.

**Comment by viendimine** [comment]
Hi Shivam , Myself Vishap raj , a Second Undergraduate Student Currently persuing Btech in Electrical Engineering From
prestigious Indian Institute Of Technology Kanpur , I want to contribute in this issue, my motivation to contribute in this issue is that as I have already done a project of Flutter Development and so I am Very Familiar to it and also I will enhance my knowldege by implementing Dark Mode widget in your project .Thanks,Waiting for a positive response.

**Comment by Redvey** [comment]
I would also like to try my hands on it.

**Comment by himanshiiiiii** [comment]
Plzz assign this issue to me I've worked on it before too

**Comment by Photon3009** [comment]
@vishapraj, I have assigned this issue to you. Please clone the repo, and if you encounter any problems at any step, let me know. @Redvey, @himanshiiiiii, you guys too, clone and run the project locally to explore the app, feel free to create your own issues as well

**Comment by himanshiiiiii** [comment]
> @vishapraj, I have assigned this issue to you. Please clone the repo, and if you encounter any problems at any step, let me know. @Redvey, @himanshiiiiii, you guys too, clone and run the project locally to explore the app, feel free to create your own issues as well

Ok

**Comment by sneha502** [comment]
I want to contribute toh this issue too, please assign me this issue #JWOC

**Comment by Photon3009** [comment]
@vishapraj  do you need one more day as this is a hard label issue, or should I assign this to someone else?

**Comment by viendimine** [comment]
Yeah , I need one more day.

**Comment by sneha502** [comment]
please assign this issue to me. #JWOC

**Comment by Photon3009** [comment]
@sneha502 are you done with the setup part?

**Comment by Photon3009** [comment]
@vishapraj any progress?

**Comment by YuvrajSingh3110** [comment]
Hey @Photon3009 i would like to work on this
Please check if this kind of dark mode would work
Also we want the dark mode natively or by clicking any button in the app itself?

![image](https://github.com/Photon3009/Auberge/assets/96365625/3c11e2d9-5d0b-4572-8b41-ef8616ba1e16)

**Comment by Photon3009** [comment]
@YuvrajSingh3110 Yes, this is cool! We can add a toggle button for switching between color schemes in the settings section
