### ISSUE TITLE
UI Bug: Overflow at Home Page

### ISSUE THREAD

**Issue by YuvrajSingh3110** [Photon3009/Auberge#6]
Hey @Photon3009 , the home page is being overflowed. I would like to fix this issue. Also in user profile section the bottom text is not clearly visible due to the bottom navigation.

![WhatsApp Image 2024-01-13 at 16 46 40_4eec0040](https://github.com/Photon3009/Auberge/assets/96365625/d783a4d2-5b28-40cb-aee0-b71d0d7e7565)
![WhatsApp Image 2024-01-13 at 16 46 40_2811c796](https://github.com/Photon3009/Auberge/assets/96365625/074a2564-33c3-4cd5-b127-fc0b453f9419)

**Comment by Photon3009** [comment]
@YuvrajSingh3110 go ahead and raise a PR. Also, for the profile screen, if you scroll down to the bottom, you can see the complete bottom text. You can fix that too

**Comment by Photon3009** [comment]
@YuvrajSingh3110 it's not recommended to make any changes to the `pubspec.lock` file. If you want to upgrade project dependencies, make changes in the `.yaml` file only when absolutely necessary

If you need to upgrade dependencies, please delete this pull request and raise a new one. When raising a new pull request, always remember to mention the associated issue number using the '#' symbol
